[project]
name = "s3-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.33",
    "environs>=14.1.1",
    "fastmcp>=2.1.0",
]
